using UnityEngine;
using System.Collections.Generic;
using UnityEngine.AI;
using Unity.AI.Navigation;

/// <summary>
/// Central automation layer for the Bergen-Belsen NavMesh environment layout.
/// Features a real-time proximity gap detector that renders visual blue lines in the Scene View
/// for unlinked road nodes within a custom threshold, and provides a one-click automated patching engine.
/// All internal code, variables, and logs are strictly maintained in English.
/// </summary>
public class BergenBelsenNavMeshAutomator : MonoBehaviour
{
    [System.Serializable]
    public class RoadPathSegment
    {
        public string roadLabelName = "Branching Segment";
        public List<Vector3> roadCenterPoints = new List<Vector3>();
    }

    [Header("💾 Legacy Data Preservation (DO NOT DELETE)")]
    [Tooltip("This list preserves your original manually placed points to ensure zero data loss.")]
    [SerializeField] private List<Vector3> roadCenterPoints = new List<Vector3>();

    [Header("📐 Architectural Hierarchy References")]
    [SerializeField] private Transform buildingsRootNode;
    [SerializeField] private Transform terrainRootNode;

    [Header("🛣️ Branching Roads Network Settings")]
    [SerializeField] private float roadWidth = 6f;
    [Tooltip("Multi-segment containers for mapping out intersections and distinct streets smoothly.")]
    [SerializeField] private List<RoadPathSegment> roadSegments = new List<RoadPathSegment>();

    [Header("🔍 Automated Gap Proximity Scanner")]
    [Tooltip("Distance threshold (in meters) below which unlinked roads are flagged as gaps and highlighted in blue.")]
    [SerializeField] private float gapDetectionRadius = 5f;

    [Header("🎨 NavMesh Area Overrides")]
    [SerializeField] private string roadAreaName = "Walkable_Roads";

    [Header("🛡️ Visual Layer Isolation (AR Culling)")]
    [SerializeField] private string roadLayerName = "MapMarkers";

    public float RoadWidth => roadWidth;
    public List<RoadPathSegment> RoadSegments => roadSegments;
    public Transform BuildingsRootNode => buildingsRootNode;

    private void Awake()
    {
        if (Application.isPlaying)
        {
            // Destroy procedural modifiers root
            GameObject modifiersRoot = GameObject.Find("Procedural_NavMesh_Modifiers_Root");
            if (modifiersRoot != null) Destroy(modifiersRoot);

            // Scan and destroy all procedural roads and autogenerated vector roads to save massive performance/RAM
            GameObject[] allGo = UnityEngine.Object.FindObjectsByType<GameObject>(FindObjectsInactive.Include);
            foreach (var go in allGo)
            {
                if (go != null && (go.name.Contains("Procedural_Roads_Container") || go.name.Contains("Autogenerated_Vector_Road")))
                {
                    Destroy(go);
                }
            }
        }
    }

#if UNITY_EDITOR
    [ContextMenu("🔄 1. Migrate Old Road Data to Segments")]
    public void MigrateOldRoadDataToSegments()
    {
        if (roadCenterPoints != null && roadCenterPoints.Count > 0)
        {
            UnityEditor.Undo.RecordObject(this, "Migrate Legacy Road Data");

            RoadPathSegment migratedSegment = new RoadPathSegment
            {
                roadLabelName = "Migrated Original Route Base",
                roadCenterPoints = new List<Vector3>(roadCenterPoints)
            };

            if (roadSegments == null) roadSegments = new List<RoadPathSegment>();
            roadSegments.Insert(0, migratedSegment);

            Debug.Log("<color=cyan>[Automator Data Protection]</color> Legacy coordinates successfully migrated into the branching segments list! Your original data is safe.");
        }
        else
        {
            Debug.LogWarning("[Automator Data Protection] No legacy data found inside 'roadCenterPoints' to migrate.");
        }
    }
#endif

    public bool IsCoordinateInsideBuildingBounds(Vector3 targetPosition, float clearanceRadius)
    {
        if (buildingsRootNode == null) return false;

        foreach (Transform building in buildingsRootNode.GetComponentsInChildren<Transform>())
        {
            if (building == buildingsRootNode) continue;

            MeshRenderer renderer = building.GetComponent<MeshRenderer>();
            if (renderer != null)
            {
                Bounds expandedBounds = renderer.bounds;
                expandedBounds.Expand(clearanceRadius);

                if (expandedBounds.Contains(new Vector3(targetPosition.x, expandedBounds.center.y, targetPosition.z)))
                {
                    return true;
                }
            }
        }
        return false;
    }

    private Vector3 SnapToTerrain(Vector3 worldPos)
    {
        // Raycast down from 200m above to find actual terrain/Cesium height in the Editor
        Vector3 origin = new Vector3(worldPos.x, worldPos.y + 200f, worldPos.z);
        if (Physics.Raycast(origin, Vector3.down, out RaycastHit hit, 400f))
        {
            return hit.point;
        }
        return worldPos; // Fallback to original point height if no hit
    }

    [ContextMenu("🛣️ 2. Generate Complete Roads Network Mesh")]
    public void GenerateAllRoadMeshesProcedurally()
    {
        int roadAreaIndex = NavMesh.GetAreaFromName(roadAreaName);
        int layerIndex = LayerMask.NameToLayer(roadLayerName);
        if (layerIndex == -1) layerIndex = 0;

        // Clean up all existing Procedural_Roads_Container in the active scene (active and inactive) to prevent duplicate generation
        GameObject[] allObjects = Resources.FindObjectsOfTypeAll<GameObject>();
        foreach (var obj in allObjects)
        {
            if (obj != null && obj.name == "Procedural_Roads_Container" && obj.scene.name != null)
            {
                DestroyImmediate(obj);
            }
        }

        GameObject containerObject = new GameObject("Procedural_Roads_Container");
        containerObject.transform.SetParent(this.transform);
        containerObject.layer = layerIndex;

        List<Vector3> combinedVerts = new List<Vector3>();
        List<int> combinedTris = new List<int>();
        float halfWidth = roadWidth / 2f;
        int structuralSegmentCounter = 0;

        foreach (RoadPathSegment segment in roadSegments)
        {
            if (segment.roadCenterPoints == null || segment.roadCenterPoints.Count < 2) continue;

            for (int i = 0; i < segment.roadCenterPoints.Count - 1; i++)
            {
                Vector3 pA = segment.roadCenterPoints[i];
                Vector3 pB = segment.roadCenterPoints[i + 1];
                float segmentLength = Vector3.Distance(pA, pB);
                int divisions = Mathf.Max(1, Mathf.RoundToInt(segmentLength)); // 1 sub-division per meter

                for (int d = 0; d < divisions; d++)
                {
                    float tCurr = (float)d / divisions;
                    float tNext = (float)(d + 1) / divisions;

                    Vector3 rawCurr = Vector3.Lerp(pA, pB, tCurr);
                    Vector3 rawNext = Vector3.Lerp(pA, pB, tNext);

                    Vector3 currentPoint = SnapToTerrain(rawCurr);
                    Vector3 nextPoint = SnapToTerrain(rawNext);

                    Vector3 directionForward = (nextPoint - currentPoint).normalized;
                    Vector3 vectorRight = Vector3.Cross(Vector3.up, directionForward).normalized;

                    Vector3 v0 = currentPoint - (vectorRight * halfWidth);
                    Vector3 v1 = currentPoint + (vectorRight * halfWidth);
                    Vector3 v2 = nextPoint - (vectorRight * halfWidth);
                    Vector3 v3 = nextPoint + (vectorRight * halfWidth);

                    int indexOffset = combinedVerts.Count;
                    combinedVerts.Add(v0); combinedVerts.Add(v1); combinedVerts.Add(v2); combinedVerts.Add(v3);

                    combinedTris.Add(indexOffset + 0); combinedTris.Add(indexOffset + 2); combinedTris.Add(indexOffset + 1);
                    combinedTris.Add(indexOffset + 1); combinedTris.Add(indexOffset + 2); combinedTris.Add(indexOffset + 3);
                }
            }
            structuralSegmentCounter++;
        }

        if (combinedVerts.Count > 0)
        {
            MeshFilter mf = containerObject.AddComponent<MeshFilter>();
            MeshRenderer mr = containerObject.AddComponent<MeshRenderer>();

            mr.sharedMaterial = new Material(Shader.Find("Sprites/Default")) { color = new Color(0.25f, 0.25f, 0.25f, 1f) };

            Mesh roadMesh = new Mesh { name = "CombinedRoadMesh" };
            roadMesh.SetVertices(combinedVerts);
            roadMesh.SetTriangles(combinedTris, 0);
            roadMesh.RecalculateNormals();
            roadMesh.RecalculateBounds();

            mf.sharedMesh = roadMesh;
            containerObject.AddComponent<MeshCollider>().sharedMesh = roadMesh;

            NavMeshModifier modifier = containerObject.AddComponent<NavMeshModifier>();
            modifier.overrideArea = true;
            modifier.area = roadAreaIndex;
        }

        NavMeshSurface activeSurface = UnityEngine.Object.FindAnyObjectByType<NavMeshSurface>(FindObjectsInactive.Include);
        if (activeSurface != null)
        {
            containerObject.transform.SetParent(activeSurface.transform);
            // Trigger automatic NavMesh bake synchronously in the editor
            activeSurface.BuildNavMesh();
            Debug.Log("<color=green>[✔ NAVMESH AUTOMATED BAKE]</color> NavMesh rebuilt successfully.");
        }

        Debug.Log($"<color=green>[✔ ROAD NETWORK GENERATED]</color> Successfully compiled and combined {structuralSegmentCounter} branching road vectors into a single mesh.");
    }

#if UNITY_EDITOR
    [ContextMenu("🧹 Clean Scene Hierarchy Duplicates")]
    public void CleanSceneHierarchyDuplicates()
    {
        // 1. Clean duplicate navmesh modifiers roots
        GameObject[] allGo = Resources.FindObjectsOfTypeAll<GameObject>();
        int modifiersDeleted = 0;
        bool keptOneModifiers = false;
        
        foreach (var go in allGo)
        {
            if (go != null && go.name == "Procedural_NavMesh_Modifiers_Root" && go.scene.name != null)
            {
                if (!keptOneModifiers)
                {
                    keptOneModifiers = true;
                }
                else
                {
                    UnityEditor.Undo.DestroyObjectImmediate(go);
                    modifiersDeleted++;
                }
            }
        }

        // 2. Clean duplicate road containers
        int roadsDeleted = 0;
        bool keptOneRoad = false;
        foreach (var go in allGo)
        {
            if (go != null && go.name == "Procedural_Roads_Container" && go.scene.name != null)
            {
                if (!keptOneRoad)
                {
                    keptOneRoad = true;
                }
                else
                {
                    UnityEditor.Undo.DestroyObjectImmediate(go);
                    roadsDeleted++;
                }
            }
        }

        // 3. Clean duplicate vector roads
        int vectorRoadsDeleted = 0;
        bool keptOneVector = false;
        foreach (var go in allGo)
        {
            if (go != null && go.name == "[Autogenerated_Vector_Road]" && go.scene.name != null)
            {
                if (!keptOneVector)
                {
                    keptOneVector = true;
                }
                else
                {
                    // If it is inside a prefab, unpacking might be needed or we can just disable it safely
                    if (UnityEditor.PrefabUtility.IsPartOfAnyPrefab(go))
                    {
                        UnityEditor.Undo.RecordObject(go, "Disable Duplicate Vector Road");
                        go.SetActive(false);
                    }
                    else
                    {
                        UnityEditor.Undo.DestroyObjectImmediate(go);
                    }
                    vectorRoadsDeleted++;
                }
            }
        }

        Debug.Log($"<color=green>[✔ HIERARCHY CLEANED]</color> Deleted/Disabled: {modifiersDeleted} duplicate modifier roots, {roadsDeleted} duplicate road containers, {vectorRoadsDeleted} duplicate vector roads.");
    }

    [ContextMenu("🧹 3. Clean Existing Cubes Under Buildings")]
    public void CleanExistingCubesUnderBuildings()
    {
        GameObject rootCubes = GameObject.Find("Procedural_NavMesh_Modifiers_Root");
        if (rootCubes == null)
        {
            Debug.LogError("[Automator Optimization] Could not find the object 'Procedural_NavMesh_Modifiers_Root' in the active scene. Generate the grid first.");
            return;
        }

        int notWalkableArea = NavMesh.GetAreaFromName("Not Walkable");
        int fixedCounter = 0;

        Transform[] allCubes = rootCubes.GetComponentsInChildren<Transform>(true);
        foreach (Transform cube in allCubes)
        {
            if (cube == rootCubes.transform) continue;

            if (IsCoordinateInsideBuildingBounds(cube.position, 0.1f))
            {
                NavMeshModifier modifier = cube.GetComponent<NavMeshModifier>();
                if (modifier != null && modifier.area != notWalkableArea)
                {
                    UnityEditor.Undo.RecordObject(modifier, "Carve Building Footprint");
                    modifier.area = notWalkableArea;
                    fixedCounter++;
                }
            }
        }

        Debug.Log($"<color=green>[✔ SCENE CLEANUP COMPLETE]</color> Audited existing modifiers. Successfully forced {fixedCounter} overlapping grass cubes to become 'Not Walkable' underneath your building placeholders!");
    }

    [ContextMenu("⚡ 4. Auto-Bridge Close Road Gaps (< 5m)")]
    public void AutoBridgeCloseRoadGaps()
    {
        if (roadSegments == null || roadSegments.Count == 0) return;

        UnityEditor.Undo.RecordObject(this, "Auto-Bridge Unlinked Road Gaps");
        int createdBridgesCount = 0;
        List<System.Collections.Generic.KeyValuePair<Vector3, Vector3>> detectedBridges = new List<System.Collections.Generic.KeyValuePair<Vector3, Vector3>>();

        // High-performance nested matrix lookup to isolate unlinked nodes within proximity bounds
        for (int sA = 0; sA < roadSegments.Count; sA++)
        {
            var segA = roadSegments[sA];
            if (segA.roadCenterPoints == null) continue;

            for (int pA = 0; pA < segA.roadCenterPoints.Count; pA++)
            {
                Vector3 posA = segA.roadCenterPoints[pA];

                for (int sB = sA; sB < roadSegments.Count; sB++)
                {
                    var segB = roadSegments[sB];
                    if (segB.roadCenterPoints == null) continue;

                    // Skip direct sequential neighbors inside the same road array path
                    int startPtB = (sA == sB) ? pA + 2 : 0;

                    for (int pB = startPtB; pB < segB.roadCenterPoints.Count; pB++)
                    {
                        Vector3 posB = segB.roadCenterPoints[pB];
                        float scalarDistance = Vector3.Distance(posA, posB);

                        if (scalarDistance > 0.05f && scalarDistance <= gapDetectionRadius)
                        {
                            detectedBridges.Add(new System.Collections.Generic.KeyValuePair<Vector3, Vector3>(posA, posB));
                        }
                    }
                }
            }
        }

        // Generate independent micro-bridge mesh injectors over the topology network
        foreach (var bridge in detectedBridges)
        {
            createdBridgesCount++;
            RoadPathSegment bridgeSegment = new RoadPathSegment
            {
                roadLabelName = $"AutoBridge_Link_{createdBridgesCount}",
                roadCenterPoints = new List<Vector3> { bridge.Key, bridge.Value }
            };
            roadSegments.Add(bridgeSegment);
        }

        if (createdBridgesCount > 0)
        {
            GenerateAllRoadMeshesProcedurally();
            Debug.Log($"<color=green>[✔ AUTO-PATCH SUCCESS]</color> Successfully patched {createdBridgesCount} geometric gaps below {gapDetectionRadius} meters by injecting micro-bridge mesh segments.");
        }
        else
        {
            UnityEditor.EditorUtility.DisplayDialog("Auto-Bridge Engine", "No unlinked road gaps below the specified distance threshold were detected.", "OK");
        }
    }
#endif

    private void OnDrawGizmos()
    {
        if (roadSegments == null) return;
        float halfWidth = roadWidth / 2f;

        // 1. Render standard sequential road connections (Yellow/Cyan meshes skeleton)
        foreach (var segment in roadSegments)
        {
            if (segment.roadCenterPoints == null || segment.roadCenterPoints.Count == 0) continue;

            for (int i = 0; i < segment.roadCenterPoints.Count; i++)
            {
                Gizmos.color = Color.yellow;
                Gizmos.DrawSphere(segment.roadCenterPoints[i], 0.4f);

                if (i < segment.roadCenterPoints.Count - 1)
                {
                    Vector3 forward = (segment.roadCenterPoints[i + 1] - segment.roadCenterPoints[i]).normalized;
                    Vector3 right = Vector3.Cross(Vector3.up, forward).normalized;

                    Gizmos.color = Color.yellow;
                    Gizmos.DrawLine(segment.roadCenterPoints[i], segment.roadCenterPoints[i + 1]);

                    Gizmos.color = Color.cyan;
                    Gizmos.DrawLine(segment.roadCenterPoints[i] - (right * halfWidth), segment.roadCenterPoints[i] + (right * halfWidth));
                }
            }
        }

        // 2. LIVE GAP VISUALIZER CORE: Highlight unlinked points within detection thresholds in clear BLUE
        for (int sA = 0; sA < roadSegments.Count; sA++)
        {
            var segA = roadSegments[sA];
            if (segA.roadCenterPoints == null) continue;

            for (int pA = 0; pA < segA.roadCenterPoints.Count; pA++)
            {
                Vector3 posA = segA.roadCenterPoints[pA];

                for (int sB = sA; sB < roadSegments.Count; sB++)
                {
                    var segB = roadSegments[sB];
                    if (segB.roadCenterPoints == null) continue;

                    int startPtB = (sA == sB) ? pA + 2 : 0;

                    for (int pB = startPtB; pB < segB.roadCenterPoints.Count; pB++)
                    {
                        Vector3 posB = segB.roadCenterPoints[pB];
                        float scalarDistance = Vector3.Distance(posA, posB);

                        if (scalarDistance > 0.05f && scalarDistance <= gapDetectionRadius)
                        {
                            Gizmos.color = Color.blue;
                            Gizmos.DrawLine(posA, posB);
                            Gizmos.DrawWireSphere(posA, 0.45f);
                            Gizmos.DrawWireSphere(posB, 0.45f);
                        }
                    }
                }
            }
        }
    }
}
